spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/todo"
    jdbc-url: ${spring.datasource.url} # This is needed
    username: tododb_user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
