version: '3.1'
services:
  tododb:
    image: postgres:11.2
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=tododb_user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
